### ISSUE TITLE
Migration to DDS textures

### ISSUE THREAD

**Issue by sumghai** [StupidChris/RealChute#36]
The upcoming 1.0 version of KSP will natively support DirectDraw Surface (DDS) textures, which can be directly loaded from disk and pushed to graphic cards, resulting in significant load time savings (compared with MBMs, PNGs and TGAs, which need to be decompressed and then recompressed to the correct format).

As such, it would be wise to transition to this texture format in the next release of this plugin.

**Notes**
 - According to KSP developer Mu:
    - RGB Diffuse textures need to be DXT1, RGBA Diffuse with Alpha textures need to be DXT5 and normal maps need to be DXTnm
    - When converting, the -flip command may be required, as DDS uses a different coordinate system to PNG/TGA (not sure if KSP 1.0 already automatically flips DDS textures to compensate, though)

**Comment by sumghai** [comment]
Okay, just used Blender and @taniwha-qf's .mu importer/exporter script, and found out that DDS textures for KSP are in fact flipped vertically:

![ksp texture format comparison](https://cloud.githubusercontent.com/assets/4993380/7365222/60cd2dc0-ede2-11e4-8fce-2544504ca0ed.png)

Should be a relatively easy fix, if the community-made KSP2DDS converter handles this properly.

Which branch should I commit the DDS textures to?

**Comment by sumghai** [comment]
EDIT: Looks like KSP2DDS does flip the resulting DDS texture as desired.

I should be able to get them to you tomorrow.

**Comment by StupidChris** [comment]
@sumghai create your own branch off from master, I'll merge it myself.

**Comment by sumghai** [comment]
Aye, will do :)

**Comment by sumghai** [comment]
Okay, made pull requests #40 and #41 for the 2.0-dev and master branches respectively.

Please test them out in-game to make sure they look okay.

**Comment by StupidChris** [comment]
Looks great, awesome work once again.

Do you think it would be possible to change the flags/icons/etc to also use DDS textures?

**Comment by sumghai** [comment]
Flags / icons / etc as DDS? I can do the texture conversion tonight, although it'll be up to you to figure out whether the plugin API supports DDS icons :)

**Comment by StupidChris** [comment]
for the Icons, I'm loading them myself. For the flags, not a clue. We'll figure out.

**Comment by sumghai** [comment]
Roger that - I'll get them to you this evening.

**Comment by sumghai** [comment]
Okay, I've ran into some problems:

 - KSP2DDS considered the part filter (32x32px) and toolbar (38x38px) icons too small to compress, and so refused to perform the conversion. I did try to force it to process the icons individually, but it resized the toolbar icon from 38x38px to 40x40px.

- RealChute only uses .truecolor files for the manufacturer part filter icons. Looking at SQUAD's own manufacturer icons, only the flag-sized ones got converted to DDS - their truecolor counterparts weren't converted.

This suggests that icons / flags are unworthy of DDS compression.

Awaiting your advice on the matter :)

**Comment by StupidChris** [comment]
Convert only the flags, I'll try converting the icons with [this](http://www.easy2convert.com/png2dds/) and see if I can get them to load in game properly.

**Comment by sumghai** [comment]
I've converted the flags and agencies to DDS - if they suffer from a loss in quality, you may revert my commit at your own discretion.

**Comment by StupidChris** [comment]
Looks all good, though the scaled version didn't appear at all, so I reverted them back to truecolor. Awesome job once mkore though, thank you! Closing this now.

**Comment by sumghai** [comment]
No worries, buddy :)

I suspect that SQUAD kept the manufacturer part filter icons as .truecolor for quality reasons - I wrote something on the forums the other day about the differences in bilinear/bicubic sampling when up/downscaling images.
