### ISSUE TITLE
Engineer's Report says there is no parachute

### ISSUE THREAD

**Issue by linuxgurugamer** [StupidChris/RealChute#42]
When it is installed, the Engineer's Report always says that the is no paracute: This command pod has crew assigned but no parachute attached.

It doesn't seem to affect the ship itself, just the engineer's report

This is RealCute 1.3.2.1

**Comment by StupidChris** [comment]
Not a bug. Just not implemented. Please make sure I didn't answer the issue before submiting a bug report. This was in 1.3.2's release notes *as well* as answered multiple times in the thread.

**Comment by mongoose11235813** [comment]
Can I try fixing it?
