### ISSUE TITLE
Parachutes work strange in 1.3.2.2b

### ISSUE THREAD

**Issue by Magik1971** [StupidChris/RealChute#45]
After 1.3.2.2b update in CKAN parachutes act strange - i can't find the words to explain what really happen.Looks like they open sideways and does not react to move vector and they are not breaking at all. Hope that will be fixed soon.

**Comment by StupidChris** [comment]
Did not follow the [bug reporting guidelines](http://forum.kerbalspaceprogram.com/threads/92229), closed. Also do not open multiple issues at once for problems that are likely linked.
