### ISSUE TITLE
Chutes not working

### ISSUE THREAD

**Issue by Unspec7** [StupidChris/RealChute#46]
Using version 1.3.2.2b. The chutes deploy just fine, but once they deploy they become useless. The chute deploys at a 90 degree angle to the craft and doesn't do anything for the remainder of the descent. Did a clean install of both KSP and RealChute, issue still persists. Applies to both vanilla chutes and RealChute ones. Chutes work fine with 1.3.2.1.

Screenshots:

Initial Deployment:
https://i.imgur.com/eA9Wdg9.jpg

Under 700m:
https://i.imgur.com/acC0WaV.jpg

KSP 1.0 on Windows 7.

**Comment by StupidChris** [comment]
Update to 1.0.2
