### ISSUE TITLE
Parachute settings not persistent through subassemblies

### ISSUE THREAD

**Issue by janmatias** [StupidChris/RealChute#48]
Hi.
I just noticed that settings for parachutes aren't saved for the stack chutes (only one I tested) with subassemblies. I can't seem to find anyone else mention this, so hopefully I'm not telling you something you already know. I'm running 1.0.2 with several other mods which of course could affect it. Is this a bug? And if so, I hope there is an easy fix, would be nice to have fully working subassemblies :)

**Comment by StupidChris** [comment]
Support dropped for 1.x, we'll see if that happens in 2.0
