### ISSUE TITLE
No configuration GUI is opened when placing a part.

### ISSUE THREAD

**Issue by HiddenKn** [StupidChris/RealChute#50]
KSP: v1.0.2.842
Problem: When placing any realchute part it doesn't open the configuration GUI
Mods Installed: 
RealChute 1.3.2.3 (+the included module manager)

Reproduction Steps: 
Place any RealChute part on any other part.

Expected behaviour: I was expecting a GUI to show up that let me configure the parachute.

Actual behaviour: The part attached without any sort of GUI popping up.

Additional information: 
The parts work normally otherwise, I just can't change their settings.
I don't see any kind of button to get to the GUI either, other than the settings gui outside of the construction building.
I tested this with a clean KSP install.

Log: 
[output_log.txt](https://gist.github.com/HiddenKn/aaee76a119e494ad6404)

**Comment by TedThompson** [comment]
Go to the action groups tab in the vab and click on the part


Sent from my Verizon Wireless 4G LTE smartphone

-------- Original message --------

**Comment by HiddenKn** [comment]
That resolved my issue, thank you!
