### ISSUE TITLE
Toolbar button disappears from the KSC scene after loading the flight scene

### ISSUE THREAD

**Issue by mongoose11235813** [StupidChris/RealChute#51]
This bug was reported on the GitHub once: #44
And on the forum too: http://forum.kerbalspaceprogram.com/threads/57988-1-0-2-Wenkel-Corporation-RealChute-Parachute-Systems-v1-3-2-3-2-05-15?p=1923346&viewfull=1#post1923346
But both reports didn't follow the guidelines and therefore didn't get any response.

I tried following the guidelines as best as I could:
Windows 8.1 64 bit
KSP 1.0.4 32 bit (the latest version)
CKAN 1.10.3 64 bit (the latest GitHub release)
RealChute 1.3.2.3 (the latest version from CKAN)
Module Manager 2.6.6 (again the latest version from CKAN)

100 % fresh install

Log: https://www.dropbox.com/s/8xnyx86nnqh4xx0/icon_missing_output_log.txt?dl=0

How to reproduce:
1. Start a new game
2. Enter the VAB and "build" one command mk 1 command pod
3. Launch
4. Recover
5. Now the real chute button is missing from the stock toolbar

Additional info:
1. This also happens if you revert to the VAB and then quit to the KSC scene.
2. This doesn't happen if you Enter and leave the VAB without going to the flight scene
3. The button disappears from all saves until you restart the KSP.exe

**Comment by StupidChris** [comment]
Support for 1.x dropped, closing.

**Comment by hillna** [comment]
I don't understand why this issue was closed. Can you please explain? Version in readme shows Realchute v1.3.2.3 for KSP v1.0.2-1.0.3. What do you mean by support for 1.x dropped?
