### ISSUE TITLE
Feature request: Field / function / variable to query "Safe to deploy"

### ISSUE THREAD

**Issue by MOARdV** [StupidChris/RealChute#52]
The 1.0.x stock chute module has a public string that I can query to determine when conditions are safe for parachute deployment.  It doesn't look like RealChute 1.x has an analogous public member (or I have been too dense to see it).  Would it be possible for RC 2.0 to have something I can query from RasterPropMonitor to determine if the RealChute 'chutes are safe to deploy?

**Comment by StupidChris** [comment]
I'll look into it

**Comment by MOARdV** [comment]
Thanks for adding this capability to 1.x.

**Comment by StupidChris** [comment]
Forgot about the issue, but yep, indeed done. It's done. It's on a per individual parachute basis, but RealChuteModule also pulls out a general approximation.
