### ISSUE TITLE
what The next person to mention 64bit support gets thrown into the black hole of shame. Along with a

### ISSUE THREAD

**Issue by REVIEWGAMINGMAN** [StupidChris/RealChute#54]
Idiot I heard that I'm currently running 64 bit because I run too many mods for recording or youtube I can understand coding can be a nightmare are you gonna allow people to help with this nightmare or or you are going continue getting messages complaints errors reports is the development open to community

**Comment by sumghai** [comment]
Unconstructive and rude. Closing.

**Comment by StupidChris** [comment]
Thanks sumghai
