### ISSUE TITLE
Missions

### ISSUE THREAD

**Issue by lordmatiz** [StupidChris/RealChute#57]
Hello.
I've just met problem with mission generated by ksp - It orders me to use radial mount chute while landed on launching pad. There is no "test" option and using chute by stage doesn't work "because I'm on the ground".

**Comment by StupidChris** [comment]
¯\_(ツ)_/¯
I don't handle mission creation bro. I'll see if I can force it to be a right click menu, but honestly, not much else I can do, just cancel those missions.
