### ISSUE TITLE
Parachute staging icon not displayed by default if part contains both RealChuteModule and ModuleDockingNode

### ISSUE THREAD

**Issue by sumghai** [StupidChris/RealChute#58]
Noticed this while working on an update for SDHI SMS.

If a part (such as my parachute-equipped docking ports) contains both RealChuteModule and ModuleDockingNode, the parachute staging icon is not displayed by default.

**Reproduction Steps**
* Start a new sandbox savegame
* Enter VAB
* Go to Utility tab and grab a *Clamp-O-Tron Docking Port - Parachute version* or *IACBM 1.25m - Parachute version*
* The parachute icon will not show up in the staging list
* Right-clicking on the part and toggling *Port: Enable Staging* unhides the parachute icon

**Desired fix**

Any part containing a RealChuteModule should always show its staging icon, regardless of any other PartModule.

**Configuration**

Windows 10 Pro 64 bit
KSP 1.0.5 32 bit, build 01028 (fresh installation)
AnimatedDecouplers v1.2.2-beta.1 (experimental release to test bugfixes)
FASA 4.50 (latest release, launch clamps only)
Hyperedit v1.4.2 (latest release)
KSPX  v0.2.9 (latest release)
ModuleManager v2.6.13 (latest release)
RealChute v1.2.3.6 (latest release)
RLA Stockalike v13.3 (latest release)
SDHI SMS 3.0.1 (latest release)
Time Control v13.2+? (experimental release by westamastaflash in Xaiier's absence)

**Log file**

[output_log.txt](https://github.com/StupidChris/RealChute/files/73496/output_log.txt)

**Additional notes**
* According to @NathanKell, KSP 1.0.5 now allows docking node decoupling to be staged, although this behaviour is disabled by default. Certain parameters could be set to enable staged docking ports by default, but I haven't been able to do so successfully even under NK's guidance.
* Another tidbit from NK:

> You (or Chris rather) need to make RealChute aware of the stage toggling functionality. You need to override the stage toggle enabled methods and perhaps some other bits. Note that each module independently interacts with the stage toggling backend, and as long as >= 1 module has staging enabled,the icon will show up and the part will stage.

**Comment by NathanKell** [comment]
See http://bugs.kerbalspaceprogram.com/issues/5689 to which both of you should have access. Note my comment midway down with updated information.

**Comment by StupidChris** [comment]
I'll look into it shortly. Sorry for the delay, it's been kinda hectic during the holidays here, heh.

**Comment by StupidChris** [comment]
Try using [this](https://github.com/StupidChris/RealChute/blob/master/Output/GameData/RealChute/Plugins/RealChute.dll?raw=true) dll, I think that should fix the issue.

**Comment by sumghai** [comment]
I'll test it tonight and report back - thanks!

**Comment by sumghai** [comment]
Fix works beautifully - adding an SDHI ParaDock into the VAB/SPH build area automatically adds the parachute icon to the staging list as desired.

Regression testing of parachute via action groups / staging button OK :)

**Comment by StupidChris** [comment]
Good, closing then :)
