### ISSUE TITLE
Adding patch information to version file

### ISSUE THREAD

**Issue by plague006** [StupidChris/RealChute#63]
For CKAN compatibility, a .[version](https://github.com/StupidChris/RealChute/blob/master/Output/GameData/RealChute/RealChute.version) file needs ksp_version listed down to the patch level. With only a major and minor version given, CKAN generates a ksp_version of `1.1.` which is invalid. It's a property I just saw emerge in this most recent release of RealChute and I'm putting an override in place for `v1.4` of RealChute which will hardcode the ksp_version compatibility to `1.1.0`.

For what it's worth if you expect RealChute to be compatible beyond `1.1.0` you can use `KSP_VERSION_MAX` to set a ceiling of `1.1.99` for example.

>KSP_VERSION - Optional, Required for MIN/MAX
Version of KSP that the add-on was made to support.
KSP_VERSION_MIN - Optional
Minimum version of KSP that the add-on supports.
Requires KSP_VERSION field to work.
KSP_VERSION_MAX - Optional
Maximum version of KSP that the add-on supports.
Requires KSP_VERSION field to work.

**Comment by StupidChris** [comment]
I know how the .version file works, but I didn't know CKAN *absolutely* needed a patch information. Since an override has been put, I'm certainly not pushing an entire update for the sole purpose of changing this, but I'll keep in mind to do it when I do push an update.

**Comment by plague006** [comment]
> I know how the .version file works

Didn't intend to imply otherwise.

> I'll keep in mind to do it when I do push an update

Appreciate it.

**Comment by StupidChris** [comment]
Merged and fixed.
