### ISSUE TITLE
Material Availability by tech   feature 

### ISSUE THREAD

**Issue by Bornholio** [StupidChris/RealChute#76]
A probably not simple request.
This doesn't work but its how i imagine it working :)
Also i Added what would be cool RO/RP0 descriptions and RP0 (Dev) tech node as an alternate

\GameData\RealChute\Materials\ParachuteMaterials.cfg
name = Silk
description = Lightweight, weak, easily ripped, but cheap. Essential for all your deathtrap concepts.
@description = First used in the 1790's its low friction and weight allow for a quick deployment. It was the default material for early parachutes. in the late 1930's drag chutes made of the material are used in aviation. Use to reduce payload cost in conditions where vehicle will be at low terminal velocity during release and temperatures will be mild.

name = Nylon
description = More solid than silk, this should land your tin cans in one piece.
@description = During World War II, the United States was unable to import silk from Japan, and parachute manufacturers began using nylon fabric. The material turned out to be superior to silk because it was more elastic, more resistant to mildew, and less expensive. This is the default material for general purpose use. Use with no special considerations.

name = Kevlar
description = The heaviest of strongest of all. Comes with a free anchor tatoo.
@description = First available in 1966 the material starting being used for military drogue and ribbon parachutes in weapon systems, Department of energy studies later found that it was an excellent material for long term storage of parachutes and highly resistant to decay. This material allows the parachute to survive in elevated temperatures and high load forces.  Use this material if a parachute needs to open in a higher speed or hot environment.
%TechRequired =  highAltitudeFlight  //Add for RO
@TechRequired =  advancedUncrewedLanding //(1972-1980)

**Comment by StupidChris** [comment]
It's in the planned stuff to implement for RealChute 2.0 which should be this summer given I have the time to do it

**Comment by Bornholio** [comment]
Okay, closing then :)
