### ISSUE TITLE
Filter by Cross-Section Profile freezes, only RealChute installed KSP 1.6.0

### ISSUE THREAD

**Issue by mlheur** [StupidChris/RealChute#82]
Fresh install KSP 1.6
Downloaded and installed https://github.com/StupidChris/RealChute/releases/tag/v1.4.7.2
launch ksp
New default save
open VAB
expand advanced controls
choose filter by cross-section profile
can no longer select parts in VAB

[output_log.txt](https://github.com/StupidChris/RealChute/files/2730001/output_log.txt)

**Comment by Starwaster** [comment]
Confirmed. Looks like there's a nullref exception in KSP.UI.Screens.PartListCategories.BulkheadProfile.ExclusionCriteria

**Comment by mlheur** [comment]
Other mods do this too, even when they are the only mod.  I just reported this to KER

https://github.com/jrbudda/KerbalEngineer/issues/34

**Comment by Starwaster** [comment]
Found the culprit. Some parts are missing bulkheadProfiles and KSP throws an exception because it's looking for that field to be populated and it isn't. I don't think this was an issue at all prior to 1.6 so something's changed on KSP's side and needs to be filed as a bug for KSP too.

**Comment by mlheur** [comment]
It may be that KSP only started (mis)handling the bulkhead profile property in 1.6; but I'm doubting that they'll agree a mod-created part that's lacking some property is a bug on their end, especially since 100% of their parts have one.

**Comment by StoneBlue** [comment]
I concur with mlheur's list of edits for the cfgs.

Also, ModuleManager updated yesterday, to v3.1.3, and I am pretty sure it addresses this stock bug, until Squad releases their own fix:

" Version 3.1.3

    Add a workaround for the 1.6.0 PartDatabase / Editor bug "

https://forum.kerbalspaceprogram.com/index.php?/topic/50533-140-16x-module-manager-313-january-8th-2019-its-dangerous-to-go-alone-take-those-cats-with-you/

**Comment by Starwaster** [comment]
Fixed
