### ISSUE TITLE
No Documentation - What is RealChute? What's the point?

### ISSUE THREAD

**Issue by MystLeissa** [StupidChris/RealChute#85]
The wiki has plenty of information on HOW to use RealChute - what I want to know is if they work like vanilla parachutes why the mod? This mod is a dependency of a mod i'm considering installing and their curseforge page directed me directly to your github so I have no clue what RealChute is in fact for. Also I have a question about mod compatibility since I currently use the mod "SafeChute" for KSP 1.7.3 - which is a parachute time warp reduction mod based on altitude and deploy height - I wonder if there would be compatibility errors with it?

**Comment by Starwaster** [comment]
They don't work just like stock. The Real Chute parts are _USED_ the same way you would use stock.

However, it is possible to configure a Real Chute part in ways that the stock chutes are not configurable.

You can for instance change the size of the canopy arbitrarily or by using Real Chute's configuration tool to automatically size them according to specified parameters. (you don't say what mod required this but it may or may not allow this type of configuration of their parts. The chutes RC comes with do. Also, the stock chutes are converted over and they also can be so configured)

I have no information about its compatibility with 'SafeChute'.

Please consult the forum thread for this mod for further information:
https://forum.kerbalspaceprogram.com/index.php?/topic/52931-17-realchute-parachute-systems-v1474-130419/
